// This is where majority of stat weighting and win probability logic lives.
// It is used by the bracket simulation logic in lib/bracket/bracket.ts
// Stat analysis generated by GPT-5.2


import type { TeamRating } from "@/lib/types/ratings";

// Defining stats

export type StatKey = "NetRtg" | "ORtg" | "DRtg" | "Luck";

export type StatConfig = {
  key: StatKey;
  label: string;
  // true if higher values should increase win likelihood
  higherIsBetter: boolean;
};

export const DEFAULT_STATS: StatConfig[] = [
  { key: "NetRtg", label: "Net Rating", higherIsBetter: true },
  { key: "ORtg", label: "Offense (ORtg)", higherIsBetter: true },
  { key: "DRtg", label: "Defense (DRtg)", higherIsBetter: false },
  { key: "Luck", label: "Luck", higherIsBetter: true },
];

export type Weights = Record<StatKey, number>; // 0..1

export type NormalizationRanges = Record<StatKey, { min: number; max: number }>;

export function computeRanges(teams: TeamRating[], stats: StatConfig[]): NormalizationRanges {
  const ranges = {} as NormalizationRanges;

  for (const s of stats) {
    let min = Number.POSITIVE_INFINITY;
    let max = Number.NEGATIVE_INFINITY;

    for (const t of teams) {
      const raw = t[s.key];
      if (typeof raw !== "number" || !Number.isFinite(raw)) continue;
      if (raw < min) min = raw;
      if (raw > max) max = raw;
    }

    if (!Number.isFinite(min) || !Number.isFinite(max)) {
      min = 0;
      max = 0;
    }

    ranges[s.key] = { min, max };
  }

  return ranges;
}

function normalize(value: number | undefined, range: { min: number; max: number }): number {
  if (value == null || !Number.isFinite(value)) return 0.5;
  if (!Number.isFinite(range.min) || !Number.isFinite(range.max)) return 0.5;
  if (range.max === range.min) return 0.5;
  const x = (value - range.min) / (range.max - range.min);
  // clamp
  return Math.max(0, Math.min(1, x));
}

export function weightedTeamScore(params: {
  team: TeamRating;
  stats: StatConfig[];
  weights: Weights;
  ranges: NormalizationRanges;
}): number {
  const { team, stats, weights, ranges } = params;

  let score = 0;
  let totalWeight = 0;

  for (const s of stats) {
    const w = weights[s.key] ?? 0;
    if (w <= 0) continue;

    const n = normalize(team[s.key], ranges[s.key]);
    const oriented = s.higherIsBetter ? n : 1 - n;

    score += w * oriented;
    totalWeight += w;
  }

  if (totalWeight === 0) {
    // No stat weights: default to rank as deterministic tie-break.
    // Lower Rk should be stronger, so convert to a positive score.
    return 1 / Math.max(1, team.Rk);
  }

  return score / totalWeight;
}

export function sigmoid(x: number): number {
  return 1 / (1 + Math.exp(-x));
}

export function winProbability(params: {
  teamA: TeamRating;
  teamB: TeamRating;
  stats: StatConfig[];
  weights: Weights;
  ranges: NormalizationRanges;
  // 0..1: 0 = purely stats; 1 = pure coin flip
  randomness: number;
  // Controls sharpness of probability curve. Larger = more deterministic.
  k?: number;
}): number {
  const { teamA, teamB, stats, weights, ranges, randomness } = params;
  const k = params.k ?? 8;

  const a = weightedTeamScore({ team: teamA, stats, weights, ranges });
  const b = weightedTeamScore({ team: teamB, stats, weights, ranges });
  const diff = a - b;

  const pStats = sigmoid(k * diff);
  const r = Math.max(0, Math.min(1, randomness));

  return (1 - r) * pStats + r * 0.5;
}
